{% set name = "pymupdf-fonts" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymupdf_fonts-{{ version }}.tar.gz
  sha256: ac12e3ec4affa35e9a0aca29135ef41c23bdbe5758c3355dac236986309e6bc6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pymupdf_fonts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pymupdf/pymupdf-fonts
  summary: Collection of font binaries for use in PyMuPDF
  license: OFL-1.1
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
